ALTER TABLE `highscore_1_0` ADD `position` SMALLINT UNSIGNED NULL DEFAULT NULL AFTER `id`;
ALTER TABLE `highscore_1_1` ADD `position` SMALLINT UNSIGNED NULL DEFAULT NULL AFTER `id`;
ALTER TABLE `highscore_1_2` ADD `position` SMALLINT UNSIGNED NULL DEFAULT NULL AFTER `id`;
ALTER TABLE `highscore_1_3` ADD `position` SMALLINT UNSIGNED NULL DEFAULT NULL AFTER `id`;
ALTER TABLE `highscore_1_4` ADD `position` SMALLINT UNSIGNED NULL DEFAULT NULL AFTER `id`;
ALTER TABLE `highscore_1_5` ADD `position` SMALLINT UNSIGNED NULL DEFAULT NULL AFTER `id`;
ALTER TABLE `highscore_1_6` ADD `position` SMALLINT UNSIGNED NULL DEFAULT NULL AFTER `id`;
ALTER TABLE `highscore_1_7` ADD `position` SMALLINT UNSIGNED NULL DEFAULT NULL AFTER `id`;

ALTER TABLE `highscore_2_0` ADD `position` SMALLINT UNSIGNED NULL DEFAULT NULL AFTER `id`;
ALTER TABLE `highscore_2_1` ADD `position` SMALLINT UNSIGNED NULL DEFAULT NULL AFTER `id`;
ALTER TABLE `highscore_2_2` ADD `position` SMALLINT UNSIGNED NULL DEFAULT NULL AFTER `id`;
ALTER TABLE `highscore_2_3` ADD `position` SMALLINT UNSIGNED NULL DEFAULT NULL AFTER `id`;
ALTER TABLE `highscore_2_4` ADD `position` SMALLINT UNSIGNED NULL DEFAULT NULL AFTER `id`;
ALTER TABLE `highscore_2_5` ADD `position` SMALLINT UNSIGNED NULL DEFAULT NULL AFTER `id`;
ALTER TABLE `highscore_2_6` ADD `position` SMALLINT UNSIGNED NULL DEFAULT NULL AFTER `id`;
ALTER TABLE `highscore_2_7` ADD `position` SMALLINT UNSIGNED NULL DEFAULT NULL AFTER `id`;
